name: Github Ci First

on:
  push:
    branches:
      - feature/*

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: checkout@v2
  build-Backend:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: build backend
        run: |
          cd /backend
          pwd
