on:
  push:
    branches:
      - feature/*
name: Github Ci First
jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: change directory
        run: cd backend
      - name: build backend
        run: docker build -t backend .
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: change directory
        run: cd frontend
      - name: build frontend
        run: docker build -t frontend .
