on:
  push:
    branches:
      - feature/*
name: Github Ci First
jobs:
  build_backend:
    runs-on: ubuntu-latest
    name: Build Backend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: build backend
        run: cd backend && docker build -t backend .
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
