on:
  push:
    branches:
      - feature/*
name: Github Ci First
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
  build-Backend:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: build backend
        run: |
          cd /backend
          pwd
