on:
  push:
    branches:
      - feature/*
  workflow_dispatch:
name: Github Ci First
jobs:
  build_backend:
    runs-on: ubuntu-latest
    name: Build Backend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: backend build
        run: cd backend && docker build -t sofiene.azurecr.io/$(git rev-parse --short HEAD)
      - name: azure regestry login
        uses: azure/docker-login@v1
        with:
          login-server: sofiene.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: push image
        run: |
          docker push sofiene.azurecr.io/$(git rev-parse --short HEAD)
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build frontend
        run: |
          cd frontend 
          docker build -t sofiene.azurecr.io/$(git rev-parse --short HEAD)
      - name: push to rca
        uses: azure/docker-login@v1
        with:
          login-server: sofiene.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: push image
        run: |
          docker push sofiene.azurecr.io/$(git rev-parse --short HEAD)
