on:
  push:
    branches:
      - feature/*
name: Github Ci First
jobs:
  build_backend:
    runs-on: ubuntu-latest
    name: Build Backend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: change dir backend
        run: cd backend 
        id : change dir
      - name : build backend
        run : docker build -t backend .
        
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: build frontend
        run: cd frontend && docker build -t frontend .
