name: integertion in develope
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: build backend
        run: docker build -t sofiene.azurecr.io/v0.0.3
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: build frontend
        run: docker build -t sofiene.azurecr.io/v0.0.3
